"""Patch RTKLIB configuration files for derived auto-QC runs."""

from __future__ import annotations

from pathlib import Path


def read_config_lines(path: Path) -> list[str]:
    """Read an RTKLIB config as individual lines."""

    return path.read_text(errors="replace").splitlines()


def get_rtklib_option(lines: list[str], key: str) -> str | None:
    """Return the uncommented value for an RTKLIB option key."""

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#") or not stripped.startswith(key):
            continue
        parts = stripped.split("=", 1)
        if len(parts) == 2:
            return parts[1].split("#", 1)[0].strip()
    return None


def set_rtklib_option(lines: list[str], key: str, value: str, comment: str | None = None) -> list[str]:
    """Set or append an RTKLIB config option."""

    output: list[str] = []
    replaced = False
    replacement = f"{key:<20}={value}"
    if comment:
        replacement += f"  # {comment}"
    for line in lines:
        stripped = line.strip()
        if not stripped.startswith("#") and stripped.startswith(key):
            output.append(replacement)
            replaced = True
        else:
            output.append(line)
    if not replaced:
        output.append(replacement)
    return output


def merge_excluded_sats(existing: str, new_sats: list[str]) -> str:
    """Merge existing and new RTKLIB `pos1-exclsats` entries."""

    merged: list[str] = []
    for sat in [*existing.split(), *new_sats]:
        clean = sat.strip()
        if clean and clean not in merged:
            merged.append(clean)
    return " ".join(merged)


def patch_config_with_autoqc(
    *,
    base_config: Path,
    out_config: Path,
    exclude_sats: list[str],
    recommended_elmask: float | None,
    source_stat: Path,
    watch_sats: list[str],
) -> None:
    """Write the exact RTKLIB config used by auto-QC pass 2."""

    lines = read_config_lines(base_config)
    existing_exclsats = get_rtklib_option(lines, "pos1-exclsats") or ""
    merged_exclsats = merge_excluded_sats(existing_exclsats, exclude_sats)
    header = [
        "# Auto-generated by um980-rtklib-pipeline --auto-sat-qc",
        f"# Source config: {base_config}",
        f"# Source stat: {source_stat}",
        "# Decision summary:",
        f"#   pos1-exclsats added: {' '.join(exclude_sats) or 'none'}",
        f"#   watch-list only: {' '.join(watch_sats) or 'none'}",
        f"#   pos1-elmask: {recommended_elmask:g}" if recommended_elmask is not None else "#   pos1-elmask: unchanged",
        "#",
    ]
    if merged_exclsats:
        lines = set_rtklib_option(lines, "pos1-exclsats", merged_exclsats, "auto-sat-qc derived exclusion list")
    if recommended_elmask is not None:
        lines = set_rtklib_option(lines, "pos1-elmask", f"{recommended_elmask:g}", "auto-sat-qc derived elevation mask")
    out_config.write_text("\n".join([*header, *lines]) + "\n", encoding="utf-8")
