import argparse
from pathlib import Path

import pytest

from um980_rtklib_pipeline import cli
from um980_rtklib_pipeline.badsat import BadSatConfig, choose_bad_sats, compute_sat_metrics, parse_rtklib_stat
from um980_rtklib_pipeline.rtklib_config_patch import patch_config_with_autoqc


def _sat_rows(
    sat: str,
    *,
    el: float,
    resp: float,
    resc: float,
    rejc: int,
    count: int = 50,
    rej_increment: bool = True,
) -> str:
    rows = []
    for index in range(count):
        rejection_counter = rejc + index // 5 if rej_increment else rejc
        rows.append(
            f"$SAT,2420,{1000 + index:.1f},{sat},1,180,{el:.1f},{resp:.3f},{resc:.3f},1,45,1,0,10,0,0,{rejection_counter}"
        )
    return "\n".join(rows) + "\n"


def test_stat_parser_and_classifier_selects_conservative_actions(tmp_path: Path):
    stat = tmp_path / "run.pass1.stat"
    stat.write_text(
        _sat_rows("G26", el=55, resp=5.5, resc=0.25, rejc=0, count=50)
        + _sat_rows("E12", el=45, resp=5.8, resc=0.05, rejc=0, count=50, rej_increment=False)
        + _sat_rows("C19", el=22, resp=5.2, resc=0.10, rejc=0, count=50, rej_increment=False)
        + _sat_rows("C20", el=23, resp=5.1, resc=0.10, rejc=0, count=50, rej_increment=False)
        + _sat_rows("G05", el=60, resp=0.3, resc=0.01, rejc=0, count=50, rej_increment=False),
        encoding="ascii",
    )

    metrics = compute_sat_metrics(parse_rtklib_stat(stat))
    decision = choose_bad_sats(metrics, BadSatConfig(max_high_el_exclude=1))

    assert "G26" in decision.exclude_sats
    assert decision.recommended_elmask == 28.0
    assert "E12" in decision.watch_sats


def test_patch_config_with_autoqc_merges_exclusions_and_elmask(tmp_path: Path):
    source = tmp_path / "base.conf"
    target = tmp_path / "derived.conf"
    stat = tmp_path / "run.pass1.stat"
    source.write_text("pos1-elmask        =15\npos1-exclsats      =G01\n", encoding="ascii")
    stat.write_text("", encoding="ascii")

    patch_config_with_autoqc(
        base_config=source,
        out_config=target,
        exclude_sats=["G26"],
        recommended_elmask=28.0,
        source_stat=stat,
        watch_sats=["E12"],
    )

    text = target.read_text(encoding="utf-8")
    assert "Auto-generated by um980-rtklib-pipeline --auto-sat-qc" in text
    assert "pos1-exclsats" in text and "G01 G26" in text
    assert "pos1-elmask" in text and "=28" in text


def test_auto_sat_qc_requires_rtklib_config(tmp_path: Path):
    args = argparse.Namespace(
        auto_sat_qc=True,
        auto_sat_qc_source="stat",
        output_format="pos",
        rtklib_path_style="unix",
        dry_run=False,
        debug=False,
        verbose=False,
    )

    with pytest.raises(ValueError, match="requires --rtkconf"):
        cli._run_rtklib_with_optional_auto_qc(
            args=args,
            rnx2rtkp="rnx2rtkp",
            rtkconf=None,
            output_file=tmp_path / "run.pos",
            rover_obs=tmp_path / "rover.obs",
            base_obs=[],
            nav_files=[],
            base_obs_arg=None,
            rtk_options=[],
            base_ecef=None,
            base_llh=None,
        )


def test_auto_sat_qc_two_pass_writes_expected_artifacts(tmp_path: Path, monkeypatch):
    rtkconf = tmp_path / "um980-autoqc-baseline.conf"
    rover = tmp_path / "rover.obs"
    base = tmp_path / "base.obs"
    nav = tmp_path / "gps.nav"
    for path in (rover, base, nav):
        path.write_text("input\n", encoding="ascii")
    rtkconf.write_text("pos1-elmask        =15\npos1-exclsats      =\nout-outstat        =residual\n", encoding="ascii")
    calls: list[Path] = []

    def fake_run_rnx2rtkp(**kwargs):
        output_file = kwargs["output_file"]
        calls.append(output_file)
        output_file.write_text("% header\n2026/05/23 00:00:00 0 0 0 1\n", encoding="ascii")
        Path(str(output_file) + ".stat").write_text(
            _sat_rows("G26", el=55, resp=5.5, resc=0.25, rejc=0, count=50)
            + _sat_rows("G05", el=60, resp=0.2, resc=0.01, rejc=0, count=50),
            encoding="ascii",
        )
        return argparse.Namespace(args=["rnx2rtkp", str(output_file)], output_file=output_file)

    monkeypatch.setattr(cli, "run_rnx2rtkp", fake_run_rnx2rtkp)
    args = argparse.Namespace(
        auto_sat_qc=True,
        auto_sat_qc_source="stat",
        max_auto_exclude=4,
        max_high_el_exclude=1,
        max_low_el_exclude=3,
        min_remaining_sats=1,
        min_remaining_constellations=1,
        output_format="pos",
        rtklib_path_style="unix",
        dry_run=False,
        debug=False,
        verbose=False,
    )

    command = cli._run_rtklib_with_optional_auto_qc(
        args=args,
        rnx2rtkp="rnx2rtkp",
        rtkconf=rtkconf,
        output_file=tmp_path / "run.pos",
        rover_obs=rover,
        base_obs=[base],
        nav_files=[nav],
        base_obs_arg=None,
        rtk_options=[],
        base_ecef=None,
        base_llh=None,
    )

    assert calls == [tmp_path / "run.pass1.pos", tmp_path / "run.pos"]
    assert command.output_file == tmp_path / "run.pos"
    assert (tmp_path / "run.pass1.stat").exists()
    assert (tmp_path / "run.stat").exists()
    assert "G26" in (tmp_path / "run.autoqc.derived.conf").read_text(encoding="utf-8")
    assert (tmp_path / "run.autoqc.report.md").exists()
    assert (tmp_path / "run.autoqc.report.json").exists()
